import localFont from "next/font/local";
import 'leaflet/dist/leaflet.css'
import "./globals.css";
// import Provider from '../components/Provider'
import Nav from '../components/Nav'
export const metadata = {
  title: "NASA Space Apps Challenge",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <main className='app'>
            <Nav />
            {children}
          </main>
        </Provider>
        
      </body>
    </html>
  );
}
